# ***Actual custom controller config, adapted for CaveX hexapod (2021 prototype)***

# IMPORTANT NOTE FROM 2022 TEAM:
# For both the 2021 and 2022 prototypes, we had to reverse the rotation direction of the femur and tibia joints, but not the coxa joint (something to do with the default +ve rotation direction on the 2XL and 2XC servos I think). To do this, the values in the 'min_pos' and 'max_pos' fields for each femur and tibia servo in the list below were swapped.
# E.g. CL_coxa_joint has min_pos 0, max_pos 4095. Whereas CL_femur_joint has min_pos 4095, max_pos 0. This reverses the rotation direction for the femur, since min > max.

# GLOBAL OPERATION PARAMETERS
loop_rate: 100                    # desired rate for joint state updates. actual rate may be less depending on number
                                  # of dynamixels on each port
control_mode: position            # control mode, either 'position', 'velocity', or 'effort'
disable_torque_on_shutdown: true  # with this enabled the motors will switch off when the controller closes
ignore_input_velocity: false      # ignore input velocity commands in position mode (no profile velocity)
diagnostics_rate: 1               # rate to publish diagnostic information
dataport_rate: 1                  # rate to read from dynamixel external dataports

# The below values are used as global defaults and are applied for each servo unless overridden in the entry for the servo below
global_max_vel: 5.0               # maximum joint speed (rad/s) (in position or velocity control)
global_torque_limit: 1.0          # maximum motor torque for all modes, given as a fraction of rated max (0-1)

# PORT AND SERVO CONFIGURATIONS
ports:

  # PORT LIST
  - name: Port_1               # name for this port in config
    device: /dev/ttyDXL       # serial device this port will communicate on
    baudrate: 1000000          # baudrate in use
    use_legacy_protocol: false # whether to use new 2.0 protocol (false) or legacy 1.0 protocol (true)
    group_read_enabled: true   # specify whether to use group comms for reading
    group_write_enabled: true  # specify whether to use group comms for writing
    servos:
        # SERVO LIST FOR THIS PORT
        - id: 1                # (ID set in servo eeprom, must be unique on this port)
          joint_name: CL_coxa_joint  # (MUST BE UNIQUE ACROSS ALL PORTS)
          #
          # The three values below are mandatory, they define the orientation and zeroing of the dynamixel:
          #
          zero_pos: 2048       # initial (0 rad) servo position (in raw encoder count)
          min_pos: 0           # minimum servo position (in raw encoder count)
          max_pos: 4095        # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
          #
          # The below arguments are all optional and override the global values:
          #
          max_vel: 5.0         # maximum joint speed (rad/s) (in position or velocity control)
          torque_limit: 1.0    # maximum motor torque for all modes, given as a fraction of rated max (0-1)

        - id: 2
          joint_name: CL_femur_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #
          # This servo doesn't have any optional values defined, the global defaults will be used
          #

        - id: 3
          joint_name: CL_tibia_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 4
          joint_name: BL_coxa_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 5
          joint_name: BL_femur_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 6
          joint_name: BL_tibia_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 7
          joint_name: AL_coxa_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 8
          joint_name: AL_femur_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 9
          joint_name: AL_tibia_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 10
          joint_name: AR_coxa_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 11
          joint_name: AR_femur_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 12
          joint_name: AR_tibia_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 13
          joint_name: BR_coxa_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 14
          joint_name: BR_femur_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 15
          joint_name: BR_tibia_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 16
          joint_name: CR_coxa_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 17
          joint_name: CR_femur_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

        - id: 18
          joint_name: CR_tibia_joint
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          #

